name = "GOF3R"
uuid = "a79dbac3-5528-457e-b637-ec38aefb197a"
authors = ["Beacon Biosignals"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
